//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.React.AI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartInvoiceDemo
    {
        public bool isProcessed { get; set; }
        public string client_name { get; set; }
        public string invoice_number { get; set; }
        public string invoice_amount { get; set; }
        public System.DateTime invoice_date { get; set; }
        public System.DateTime due_date { get; set; }
        public string description { get; set; }
        public string invoice_url { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    }
}
