//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.React.AI.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebApiReactAI20200409083751_dbEntitiesMain : DbContext
    {
        public WebApiReactAI20200409083751_dbEntitiesMain()
            : base("name=WebApiReactAI20200409083751_dbEntitiesMain")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SmartInvoiceDemo> SmartInvoiceDemoes { get; set; }
    }
}
